# VideoHub Pro Enterprise — Gradle Properties
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
# Configuration cache disabled — Hilt's AggregateDepsTask is not fully compatible
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
kotlin.incremental=true

# KSP
ksp.incremental=true
